#!/usr/bin/python

import lmdb
from argparse import ArgumentParser

parser = ArgumentParser(description='List keys contained in an LMDB database')

parser.add_argument('-k', '--key', type=str, required=True,
                    help="Key for the image to extract")
parser.add_argument('-o', '--output_jpeg', type=str, required=True,
                    help="Output path for JPEG image")

parser.add_argument(dest="lmdb_file", action="store", 
                  help="Target LMDB file" )

options = parser.parse_args()

lmdb_file = options.lmdb_file

lmdb_env = lmdb.open(lmdb_file, subdir=False)
lmdb_txn = lmdb_env.begin()
lmdb_cursor = lmdb_txn.cursor()

found_it = False
for key, value in lmdb_cursor:

	if key == options.key:
		print "Extracting image: %s to %s" % (key, options.output_jpeg)
		with open(options.output_jpeg, 'w') as of:
			of.write(value)
			found_it = True
		break

if not found_it:
	print "Could not find key in database"


