#!/usr/bin/env python3

from argparse import ArgumentParser
import lmdb

parser = ArgumentParser(description='List keys contained in an LMDB database')
parser.add_argument('-k', '--key', type=str, required=True, help='Key for the image to extract')
parser.add_argument('-o', '--output_jpeg', type=str, required=True, help='Output path for JPEG image')
parser.add_argument('lmdb_file', type=str, help='Target LMDB file')
options = parser.parse_args()

lmdb_file = options.lmdb_file
lmdb_env = lmdb.open(lmdb_file, subdir=False)
lmdb_txn = lmdb_env.begin()
lmdb_cursor = lmdb_txn.cursor()

found_it = False
for key, value in lmdb_cursor:
	if key == options.key.encode():
		print(f'Extracting image: {key.decode()} to {options.output_jpeg}')
		with open(options.output_jpeg, 'wb') as of:
			of.write(value)
			found_it = True
		break

if not found_it:
	print('Could not find key in database')
